version: "3.8"

services:
  web:
    image: syedfaizan8/velocitype:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../.env.production
    environment:
      NODE_ENV: production
